# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Update Ubuntu software
        run: sudo apt update
      # Install NodeJS
      - name: Install NodeJS and NPM
        run: |
          sudo apt install nodejs
          sudo apt install npm
      # Verify NodeJS version
      - name: Verify NodeJS and NPM version 
        run: |
          node -v
          npm --version
      # Install Salesforce CLI tool
      - name: Install Salesforce CLI tool
        run: npm install --global @salesforce/cli
      # Verify Salesforce CLI tool version
      - name: Verify Salesforce CLI tool version
        run: sf --version
      # Decrypt encrypted file server key into "server.key" file
      - name: Set env variables
        run: |
          export DECRYPTION_KEY=${{secrets.DECRYPTION_KEY}}
          export DECRYPTION_IV=${{secrets.DECRYPTION_IV}}
      # Decrypt encrypted file server key into "server.key" file
      - name: Decrypt encrypted file server key into "server.key" file
        run: openssl enc -nosalt -aes-256-cbc -d -in ./server.key.enc -out ./server.key -base64 -K ${{secrets.DECRYPTION_KEY}} -iv ${{secrets.DECRYPTION_IV}}
      # Login into Salesforce using username and digital certificate key
      - name: Login into Salesforce using username and digital certificate key
        run: sf org login jwt --client-id $SF_SECRET_KEY_FOR_CLIENT_ID -o $SF_USERNAME --jwt-key-file ./server.key --instance-url https://test.salesforce.com
      # # Deploy project into Salesforce ORG
      # - name: Deploy project into Salesforce ORG
      #   run: sf project deploy start -x force-app/main/default/package.xml -l RunSpecifiedTests -t $TESTCLASSES -o $SF_USERNAME
      # Logout from Salesforce ORG
      - name: Logout from Salesforce ORG
        run: sf org logout -p -o $SF_USERNAME